package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

const generatedPrefix = "zz_generated_"

// maxValuesInComment limita quantos valores válidos aparecem no comentário
// de um campo; listas maiores viram só a contagem.
const maxValuesInComment = 12

type field struct {
	Name    string
	Type    string
	Tag     string
	Comment string
}

type structDef struct {
	Package    string
	SDKVersion string
	Class      string
	Type       string
	RN         string
	Fields     []field
}

var fileTmpl = template.Must(template.New("mo").Parse(`// Code generated by mogen. DO NOT EDIT.
// Fonte: ucsmsdk {{.SDKVersion}}, classe {{.Class}}.

package {{.Package}}

import "encoding/xml"

// {{.Type}} representa a classe {{.Class}} do UCS Manager.
// RN: {{.RN}}
type {{.Type}} struct {
	XMLName xml.Name ` + "`xml:\"{{.Class}}\"`" + `
{{- range .Fields}}
	{{.Name}} {{.Type}} ` + "`{{.Tag}}`" + `{{if .Comment}} // {{.Comment}}{{end}}
{{- end}}
}

// {{.Type}}List recebe uma lista de {{.Class}} vinda de outConfigs
// (por exemplo, numa chamada configResolveClass).
type {{.Type}}List struct {
	XMLName xml.Name
	Items   []{{.Type}} ` + "`xml:\"{{.Class}}\"`" + `
}
`))

// buildStruct monta a definição de uma classe: atributos (sem os
// internal) e um slice para cada filho que também está no schema.
func buildStruct(s *Schema, c Class, pkg string) (structDef, error) {
	def := structDef{
		Package:    pkg,
		SDKVersion: s.SDKVersion,
		Class:      c.Name,
		Type:       typeName(c.Name),
		RN:         c.RN,
	}

	used := map[string]string{"XMLName": "(reservado)"}
	add := func(f field, origin string) error {
		if prev, dup := used[f.Name]; dup {
			return fmt.Errorf("%s: campo Go %q gerado por %q e por %q", c.Name, f.Name, prev, origin)
		}
		used[f.Name] = origin
		def.Fields = append(def.Fields, f)
		return nil
	}

	for _, p := range c.Props {
		if p.Access == "internal" {
			continue
		}
		f := field{
			Name:    fieldName(p.XML),
			Type:    "string",
			Tag:     fmt.Sprintf(`xml:"%s,attr,omitempty"`, p.XML),
			Comment: valuesComment(p.Values),
		}
		if err := add(f, p.XML); err != nil {
			return def, err
		}
	}

	for _, ch := range s.GeneratedChildren(c) {
		t := typeName(ch)
		f := field{Name: t, Type: "[]" + t, Tag: fmt.Sprintf(`xml:"%s"`, ch)}
		if err := add(f, "filho "+ch); err != nil {
			return def, err
		}
	}
	return def, nil
}

func valuesComment(values []string) string {
	switch n := len(values); {
	case n == 0:
		return ""
	case n > maxValuesInComment:
		return fmt.Sprintf("Valores válidos: %d opções (ver schema).", n)
	default:
		return "Valores válidos: " + strings.Join(values, ", ") + "."
	}
}

// generate grava um arquivo por classe em outDir e remove arquivos
// gerados antigos de classes que saíram do schema.
func generate(s *Schema, outDir, pkg string) error {
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return err
	}
	stale, err := filepath.Glob(filepath.Join(outDir, generatedPrefix+"*.go"))
	if err != nil {
		return err
	}
	for _, f := range stale {
		if err := os.Remove(f); err != nil {
			return err
		}
	}

	for _, name := range s.Names() {
		def, err := buildStruct(s, s.Classes[name], pkg)
		if err != nil {
			return err
		}
		var buf bytes.Buffer
		if err := fileTmpl.Execute(&buf, def); err != nil {
			return fmt.Errorf("%s: template: %w", name, err)
		}
		src, err := format.Source(buf.Bytes())
		if err != nil {
			return fmt.Errorf("%s: código gerado inválido: %w\n%s", name, err, buf.String())
		}
		dest := filepath.Join(outDir, generatedPrefix+name+".go")
		if err := os.WriteFile(dest, src, 0o644); err != nil {
			return err
		}
	}
	return nil
}
